modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
logoFile="paulstweaks.png"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
    modId="paulstweaks"
    version="${version}"
    displayName="Paul's Tweaks"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
    authors="TheCoolestPaul and, Cheese"
    credits="The Boys"
    description='''
    Some stuff I use for my modpacks with the boys
    '''

[[dependencies.paulstweaks]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"